#!/usr/bin/env bash
# Allow user `pi` to run `nmcli` without typing a password.
# Required because the BLE provisioning script swaps Wi-Fi credentials and
# the Pi user is rarely in the polkit group that NetworkManager checks.
#
# Usage:  sudo bash scripts/install_nmcli_sudoers.sh
set -euo pipefail

if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root (use sudo)." >&2
    exit 1
fi

TARGET_USER="${SUDO_USER:-pi}"
RULE_FILE="/etc/sudoers.d/koda-nmcli"

# Resolve the actual path so the rule survives a $PATH change.
NMCLI_PATH="$(command -v nmcli || echo /usr/bin/nmcli)"

cat > "$RULE_FILE" <<EOF
# Generated by codeRaspberry/scripts/install_nmcli_sudoers.sh
# Lets KODA's BLE provisioning script switch Wi-Fi networks unattended.
${TARGET_USER} ALL=(root) NOPASSWD: ${NMCLI_PATH}
EOF
chmod 0440 "$RULE_FILE"

# Validate the new sudoers file before we trust it.
if ! visudo -cf "$RULE_FILE" >/dev/null; then
    echo "Sudoers rule failed validation; removing $RULE_FILE" >&2
    rm -f "$RULE_FILE"
    exit 1
fi

echo "Installed $RULE_FILE → user '${TARGET_USER}' can now run '${NMCLI_PATH}' without password."
echo "Test: sudo -n nmcli general status"
